include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: gis
  IMAGE_NAME: atmoz/sftp
  IMAGE_TAG: alpine

.deploy:
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG}
      SFTP_USERS=${SFTP_USERS} PUBLIC_PORT=${PUBLIC_PORT}
