version: '3.5'

services:
  sftp:
    image: atmoz/sftp:alpine
    command: "${SFTP_USERS}"
    networks:
      - gis-net
    ports:
      - target: 22
        published: ${PUBLIC_PORT}
        mode: host
    volumes:
        - geoserver-vol:/home/geoserver/geoserver
    command: "${SFTP_USERS}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 52M

networks:
  gis-net:
    external: true
