version: '3.5'

services:
  sftp:
    image: atmoz/sftp:alpine
    command: "${SFTP_USERS}"
    networks:
      - gis-net
    ports:
      - target: 22
        published: ${PUBLIC_PORT}
        mode: host
    volumes:
        - geoserver-vol:/home/geoserver/geoserver

networks:
  gis-net:
    external: true
