version: '3.5'

services:
  sftp:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 8M
        reservations:
          memory: 7M

volumes:
  geoserver-vol:
    name: "geoserver-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
