version: '3.5'

services:
  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "${PORT}:22"
    volumes:
        - geoserver-vol:/home/geoserver/geoserver
    command: "${SFTP_USERS}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3