version: '3.5'

services:
  sftp:
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  geoserver-vol:
    name: geoserver-maxio-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
      perfmode: maxio
